// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/topper-mobile/ChapterPage.tsx": () => import("../components/mockups/topper-mobile/ChapterPage.tsx"),
  "./components/mockups/topper-mobile/CommunityHub.tsx": () => import("../components/mockups/topper-mobile/CommunityHub.tsx"),
  "./components/mockups/topper-mobile/Dashboard.tsx": () => import("../components/mockups/topper-mobile/Dashboard.tsx"),
  "./components/mockups/topper-mobile/ProfileSettings.tsx": () => import("../components/mockups/topper-mobile/ProfileSettings.tsx"),
  "./components/mockups/topper-mobile/ProgressStats.tsx": () => import("../components/mockups/topper-mobile/ProgressStats.tsx")
};
